name: CI
on: push
jobs:
  build:
    strategy:
      matrix:
        py: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: pytest
        run: |
          cd /home/runner/work/daggerml-cli/daggerml-cli
          PYTHONPATH=. python -m pytest -m "not slow" .
      - name: Install ruff
        run: pip install ruff
      # Update output format to enable automatic inline annotations.
      - name: Run Ruff
        run: ruff check --output-format=github .
